//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *DevSandboxTemplate) DeepCopyInto(out *DevSandboxTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	if in.Spec.ServicePorts != nil {
		out.Spec.ServicePorts = append([]ServicePort(nil), in.Spec.ServicePorts...)
	}
	in.Spec.SandboxBlueprint.DeepCopyInto(&out.Spec.SandboxBlueprint)
	if in.Status.Conditions != nil {
		out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	}
}

func (in *DevSandboxTemplate) DeepCopy() *DevSandboxTemplate {
	if in == nil {
		return nil
	}
	out := new(DevSandboxTemplate)
	in.DeepCopyInto(out)
	return out
}

func (in *DevSandboxTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DevSandboxTemplateList) DeepCopyInto(out *DevSandboxTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DevSandboxTemplate, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *DevSandboxTemplateList) DeepCopy() *DevSandboxTemplateList {
	if in == nil {
		return nil
	}
	out := new(DevSandboxTemplateList)
	in.DeepCopyInto(out)
	return out
}

func (in *DevSandboxTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DevSandbox) DeepCopyInto(out *DevSandbox) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	if in.Status.LastActivityTime != nil {
		out.Status.LastActivityTime = in.Status.LastActivityTime.DeepCopy()
	}
	if in.Status.IdleDeadline != nil {
		out.Status.IdleDeadline = in.Status.IdleDeadline.DeepCopy()
	}
	if in.Status.StoppedAt != nil {
		out.Status.StoppedAt = in.Status.StoppedAt.DeepCopy()
	}
	if in.Status.RetentionDeadline != nil {
		out.Status.RetentionDeadline = in.Status.RetentionDeadline.DeepCopy()
	}
	if in.Status.Conditions != nil {
		out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	}
}

func (in *DevSandbox) DeepCopy() *DevSandbox {
	if in == nil {
		return nil
	}
	out := new(DevSandbox)
	in.DeepCopyInto(out)
	return out
}

func (in *DevSandbox) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DevSandboxList) DeepCopyInto(out *DevSandboxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DevSandbox, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *DevSandboxList) DeepCopy() *DevSandboxList {
	if in == nil {
		return nil
	}
	out := new(DevSandboxList)
	in.DeepCopyInto(out)
	return out
}

func (in *DevSandboxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DevSandboxUserQuota) DeepCopyInto(out *DevSandboxUserQuota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	if in.Status.Reservations != nil {
		out.Status.Reservations = append([]QuotaReservation(nil), in.Status.Reservations...)
	}
	if in.Status.Conditions != nil {
		out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	}
}

func (in *DevSandboxUserQuota) DeepCopy() *DevSandboxUserQuota {
	if in == nil {
		return nil
	}
	out := new(DevSandboxUserQuota)
	in.DeepCopyInto(out)
	return out
}

func (in *DevSandboxUserQuota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DevSandboxUserQuotaList) DeepCopyInto(out *DevSandboxUserQuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DevSandboxUserQuota, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *DevSandboxUserQuotaList) DeepCopy() *DevSandboxUserQuotaList {
	if in == nil {
		return nil
	}
	out := new(DevSandboxUserQuotaList)
	in.DeepCopyInto(out)
	return out
}

func (in *DevSandboxUserQuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DevSandboxJob) DeepCopyInto(out *DevSandboxJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	if in.Status.StartedAt != nil {
		out.Status.StartedAt = in.Status.StartedAt.DeepCopy()
	}
	if in.Status.CompletedAt != nil {
		out.Status.CompletedAt = in.Status.CompletedAt.DeepCopy()
	}
	if in.Status.ExitCode != nil {
		value := *in.Status.ExitCode
		out.Status.ExitCode = &value
	}
	if in.Status.Conditions != nil {
		out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	}
}

func (in *DevSandboxJob) DeepCopy() *DevSandboxJob {
	if in == nil {
		return nil
	}
	out := new(DevSandboxJob)
	in.DeepCopyInto(out)
	return out
}

func (in *DevSandboxJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DevSandboxJobList) DeepCopyInto(out *DevSandboxJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DevSandboxJob, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *DevSandboxJobList) DeepCopy() *DevSandboxJobList {
	if in == nil {
		return nil
	}
	out := new(DevSandboxJobList)
	in.DeepCopyInto(out)
	return out
}

func (in *DevSandboxJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
