[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$ApiUrl,
    [Parameter(Mandatory)][string]$WebUrl,
    [ValidateSet('device-flow', 'github-cli-static')]
    [string]$AuthMode = 'github-cli-static',
    [string]$GitHubLogin,
    [string]$DefaultTemplate = 'standard',
    [string]$EnvironmentPath = (Join-Path $PSScriptRoot '..\.env'),
    [string]$ExecutablePath = (Join-Path $PSScriptRoot '..\devsandbox.exe')
)

$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $true

function Assert-Endpoint {
    param([Parameter(Mandatory)][string]$Name, [Parameter(Mandatory)][string]$Value)

    $uri = $null
    if (-not [Uri]::TryCreate($Value, [UriKind]::Absolute, [ref]$uri) -or
        $uri.Scheme -ne 'https' -or [string]::IsNullOrWhiteSpace($uri.Host) -or
        $uri.PathAndQuery -ne '/') {
        throw "$Name must be an HTTPS origin URL without a path or query."
    }
    return $uri.AbsoluteUri.TrimEnd('/')
}

$resolvedApiUrl = Assert-Endpoint -Name ApiUrl -Value $ApiUrl
$resolvedWebUrl = Assert-Endpoint -Name WebUrl -Value $WebUrl
if ($resolvedApiUrl -eq $resolvedWebUrl) {
    throw 'API and web URLs must use separate origins.'
}
if ($DefaultTemplate -notmatch '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$') {
    throw 'DefaultTemplate must be a DNS-safe template name.'
}
if ($AuthMode -eq 'github-cli-static' -and $GitHubLogin -notmatch '^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})$') {
    throw 'GitHubLogin is required for github-cli-static mode.'
}
if (-not (Get-Command go -ErrorAction SilentlyContinue)) {
    throw 'Local CLI build requires Go from the version declared in go.mod.'
}

$repositoryRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$environmentFullPath = [IO.Path]::GetFullPath($EnvironmentPath)
$executableFullPath = [IO.Path]::GetFullPath($ExecutablePath)
$environmentDirectory = Split-Path -Parent $environmentFullPath
$executableDirectory = Split-Path -Parent $executableFullPath
New-Item -ItemType Directory -Force -Path $environmentDirectory, $executableDirectory | Out-Null

$environmentTemporaryPath = "$environmentFullPath.$PID.tmp"
$executableTemporaryPath = "$executableFullPath.$PID.tmp"
$configuration = @"
# Generated by scripts/configure-local.ps1. This file contains no credentials.
DEVSANDBOX_API_URL=$resolvedApiUrl
DEVSANDBOX_WEB_URL=$resolvedWebUrl
DEVSANDBOX_AUTH_MODE=$AuthMode
$(if ($AuthMode -eq 'github-cli-static') { "DEVSANDBOX_GITHUB_LOGIN=$GitHubLogin" })
DEVSANDBOX_DEFAULT_TEMPLATE=$DefaultTemplate
"@

try {
    Push-Location $repositoryRoot
    try {
        & go build -trimpath -o $executableTemporaryPath ./cmd/devsandbox
        if ($LASTEXITCODE -ne 0) {
            throw "Local DevSandbox CLI build failed with exit code $LASTEXITCODE."
        }
    }
    finally {
        Pop-Location
    }

    [IO.File]::WriteAllText(
        $environmentTemporaryPath,
        "$($configuration.TrimEnd())`n",
        [Text.UTF8Encoding]::new($false)
    )
    Move-Item -LiteralPath $executableTemporaryPath -Destination $executableFullPath -Force
    Move-Item -LiteralPath $environmentTemporaryPath -Destination $environmentFullPath -Force
}
finally {
    Remove-Item -LiteralPath $environmentTemporaryPath, $executableTemporaryPath -Force -ErrorAction SilentlyContinue
}

Write-Host "Local DevSandbox is ready: $executableFullPath up"
